### ISSUE TITLE
Milestone 2: To-Do List

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/get-resstock#29]
Checklist:
- [ ] [Jeff on central HPWH; ? for other categories] Update 2025 and 2028 files for [_projected_ code updates](https://github.com/NREL/get-resstock/issues/22)
- [ ] [Jeff] Consolidate/summarize all 2022 Title 24 / 20 spreadsheets into a single spreadsheet or document
  - Format should consider displaying differences between 2022, 2025, 2028
- [ ] [Joe] Finalize projection tool input files
  - Scenarios 1 - 4: https://github.com/NREL/buildstock-projections/pull/79
  - Scenarios 5 - 6: https://github.com/NREL/buildstock-projections/pull/110
- [x] [Prateek] Finish ability to summarize buildstock csv files
  - Side-by-side visualizations across years
  - Underlying data files
- [ ] [Cu] Run the projections and create all 6 buildstock csv files
  - Remember to [downselect resulting buildstock csv files](https://github.com/NREL/buildstock-projections/blob/title24/tests/test_files/project_CA/downselect_buildstocks.py) to MF only, and not San Diego (county) or Long Beach (city)
- [ ] [Cu] Run [check_buildstock.rb](https://github.com/NREL/get-resstock/blob/develop/test/check_buildstock.rb) on all buildstock csv files. Use [this branch's options_lookup](https://github.com/NREL/get-resstock/pull/13)
- [x] [Joe] Finish remaining projection tool parameters
  - Get `County and PUMA` options for all cities that don't have ResStock `City` options
- [x] [Joe] Review/merge all [Title 24 / 20 PRs](https://github.com/NREL/get-resstock/pulls)
